### ISSUE TITLE
Claim that updates.jenkins.io certificate is sometimes expiring

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3017]
### Service(s)

Update center

### Summary

The user reporting [JENKINS-66788](https://issues.jenkins.io/browse/JENKINS-66788) says that the update center sometimes returns an invalid SSL certificate.

I'm not skilled enough in evaluating SSL services to decide if the issue is due to a user configuration error or a server error

### Reproduction steps

1. Check SSL certificate for https://updates.jenkins.io repeatedly
2. User says that sometimes it returns an invalid certificate authority

I'm unable to duplicate the issue.  The checks that I run consistently show that the correct SSL certificate is returned.

**Comment by dduportal** [comment]
> Note, without the servername you always get the 'Kubernetes_Ingress_Controller_Fake_Certificate'.

This is related to https://en.wikipedia.org/wiki/Server_Name_Indication . If there are no SNI when establishing a TLS handshake (case of the command `openssl s_client <...>` command), then the reverse-proxy cannot guess which vhost configuration to use, so it falls back on a "default" vhost.
When establishing an HTTP(S) connection, the reverse-proxy select the vhost configuration based on the "Host" header, or fallback to the SNI if there was a TLS handshake.

- For get.jenkins.io, hosted in a Kubernetes cluster, then the default vhost is the default-backend of the nginx ingress-controller with no associated hostname (which is the goal).
- For updates.jenkins.io, the apache server defaults to the pkg.origin.jenkins.io service.

Once a vhost configuration is picked, then the certificate is also picked based on this configuration.

=> It's a clue: we need the user's public IP to check the logs for their Host header. If request are emitted with an invalid host header (and no SNI), usually sign of an old HTTP client (Internet Explorer, a "corporate secured appliance proxy", etc.)

**Comment by dduportal** [comment]
Additionnaly, our TLS grading is "B" for updates.jenkins.io as per https://www.ssllabs.com/ssltest/analyze.html?d=updates.jenkins.io&hideResults=on .

=> Supporting the old TLS v1.0 and v1.1 is not expected and should not be kept.

**Comment by apton-sooraj** [comment]
Docker build is failing.
`Step 11/11 : RUN jenkins-plugin-cli --plugins "blueocean:1.25.5 docker-workflow:1.28"
 ---> Running in 35c2ace9f94a
Jun 24, 2022 7:22:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://updates.jenkins.io:443: The target server failed to respond
Jun 24, 2022 7:22:08 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://updates.jenkins.io:443
` 
I tried to run an official image from the docker hub. That is also failing
` docker run -p 8080:8080 -p 50000:50000 jenkinsci/jenkins`
![image](https://user-images.githubusercontent.com/99787341/175486938-38a67a86-d91b-4ca9-893b-d8998367ace4.png)
New Installations are not working (docker).

**Comment by dduportal** [comment]
Hi @apton-sooraj, thanks for reporting the error.

Your message is not related to this issue, could you open a separate one please?

**Comment by dduportal** [comment]
Closing as:
- No answer from the requester on JIRA
- Should be fixed by https://github.com/jenkins-infra/helpdesk/issues/3017

**Comment by mbtc100** [comment]
I have attempted to upgrade Jenkins again this month and was unable to do so before now.

For info I still encountered the SSL errors from the update site, but I have switched to running Jenkins in a later JDK which has resolved the issue.

I think perhaps that OpenJDK-11 may have been loosing header information on cached connections, as calls would succeed for some time then fail consistently. A restart of Jenkins would restore the connection and allow the completion of updates.
