### ISSUE TITLE
[ci.jenkins.io] Use Spot instances for VM agents to decrease costs

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4598]
### Service(s)

ci.jenkins.io

### Summary

We used to have spot instances in EC2 and Azure VM agents. It helps drastically decrease the billing, but at the expense of potential build retries.

@smerle33 did implement a fix in the ATH: https://github.com/jenkinsci/acceptance-test-harness/blob/ecaf4fc38523b77e0997daa4285999965276a3e2/Jenkinsfile#L115-L123 which retries if the spot instance is reclaimed.

In order to switch to Spot instances with the EC2 plugin we have to:

- Update our current setup to support Spot Instance, as hinted in the EC plugin configuration: https://plugins.jenkins.io/ec2/#plugin-content-spot-instances
  - Tl;DR;  we have to set up agent as inbound (instead of SSH) with cloud init setting up a service to launch the agent
  - We did that on Azure so it should be pretty easy, but requires updating our Puppet JCasc template (and eventually packer images AMIs)
  - Good point: it will help by sequentializing the cloud init and then agent startup!
- Update the template to have both "ondemand" and "nonspot" series
- Update the `buildPlugin()` pipeline library to introduce the same retry technique as in ATH

**Comment by dduportal** [comment]
For info: I've merged https://github.com/jenkins-infra/jenkins-infra/pull/3971 because of https://github.com/jenkins-infra/helpdesk/issues/4600. Tested and works well!

I've also disabled manually the fallback to ondemand instances and disabled puppet on ci.jio.

**Comment by smerle33** [comment]
![Image](https://github.com/user-attachments/assets/4d2d4fd4-1802-4b4b-89ec-b2462fc1a08e)

**Comment by smerle33** [comment]
we still have a few usage of nonspot instances that we need to investigate

**Comment by smerle33** [comment]
after simplifying the labels with https://github.com/jenkins-infra/jenkins-infra/pull/3983 we use them for 2 spots tries and the nonspot with https://github.com/jenkins-infra/pipeline-library/pull/917

tested here https://ci.jenkins.io/job/Plugins/job/blueocean-plugin/job/master/524

**Comment by smerle33** [comment]
as per quota limit, we need to increase the limit, here is the link to our demand to upgrade to 1000: https://support.console.aws.amazon.com/support/home#/case/?displayId=174283501300384

**Comment by smerle33** [comment]
use spot instances on PACKER-IMAGES

**Comment by dduportal** [comment]
As per the billing costs we reported in https://github.com/jenkins-infra/helpdesk/issues/4600#issuecomment-2760943495, it looks like the task here is done:

- We still have a 24-48h delay for the packer spot instances (`t3.xlarge`) to be changed from `BoxUsage` to `SpotUsage` as it was only merged yesterday: https://github.com/jenkins-infra/packer-images/pull/1824
- The remaining "top level" `BoxUsage` are the static VMs which are not candidate for spot (1 VM for ci.jenkins.io controller and 2 `applications` VM in EKS)
